name: pull-request
on:
  pull_request: {}
jobs:
  test:
    name: 'test'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_ed25519
        # this is done automatically by terraform
        known_hosts: unnecessary
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.13.5
        # https://github.com/gruntwork-io/terragrunt/issues/1202
        # https://github.com/hashicorp/setup-terraform
        terraform_wrapper: false
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.8
    - name: test
      run: make test
